name: BuildAndPublishNuget

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 7
      uses: actions/setup-dotnet@4d4a70f4a5b2a5a5329f13be4ac933f2c9206ac0
      with:
        dotnet-version: 7.0.x
    - name: Add VideoLan-Preview-Nuget-Source
      run: dotnet nuget add source "https://f.feedz.io/videolan/preview/nuget/index.json"
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal --filter TestCategory\!=NeedsSpecificBinaries
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.2  
      with: 
        PROJECT_FILE_PATH: Barembo.Connector/Barembo.Connector.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
