name: BuildAndPublish

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal --filter TestCategory\!=NeedsSpecificBinaries
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.2  
      with: 
        PROJECT_FILE_PATH: Barembo.Connector/Barembo.Connector.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
